# SQLite version 3.x
#   gem install sqlite3
defaults: &defaults
  adapter: <%= /java/ === RUBY_PLATFORM ? "mysql" : "mysql2" %>
  host: localhost
  username: root
  password: a
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *defaults
  database: apposs_development

test: &test
  <<: *defaults
  database: apposs_test

production:
  <<: *defaults
  database: apposs_production


cucumber:
  <<: *test
