# SQLite version 3.x
#   gem install sqlite3
defaults: &defaults
  adapter: mysql
  host: localhost
  username: root
  password: a
  encoding: utf8
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *defaults
  database: apposs_development

test:
  <<: *defaults
  database: apposs_test

production:
  <<: *defaults
  database: apposs_production


